//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace _3342DevStepFinal.Hotels {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HotelServiceSoap", Namespace="http://tempuri.org/")]
    public partial class HotelService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetHotelsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRoomsByHotelOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindRoomsOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindRoomsByHotelOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckDatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReserveOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HotelService() {
            this.Url = global::_3342DevStepFinal.Properties.Settings.Default._3342DevStepFinal_Hotels_HotelService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetHotelsCompletedEventHandler GetHotelsCompleted;
        
        /// <remarks/>
        public event GetRoomsByHotelCompletedEventHandler GetRoomsByHotelCompleted;
        
        /// <remarks/>
        public event FindRoomsCompletedEventHandler FindRoomsCompleted;
        
        /// <remarks/>
        public event FindRoomsByHotelCompletedEventHandler FindRoomsByHotelCompleted;
        
        /// <remarks/>
        public event CheckDatesCompletedEventHandler CheckDatesCompleted;
        
        /// <remarks/>
        public event ReserveCompletedEventHandler ReserveCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHotels", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetHotels(string city, string state) {
            object[] results = this.Invoke("GetHotels", new object[] {
                        city,
                        state});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetHotelsAsync(string city, string state) {
            this.GetHotelsAsync(city, state, null);
        }
        
        /// <remarks/>
        public void GetHotelsAsync(string city, string state, object userState) {
            if ((this.GetHotelsOperationCompleted == null)) {
                this.GetHotelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHotelsOperationCompleted);
            }
            this.InvokeAsync("GetHotels", new object[] {
                        city,
                        state}, this.GetHotelsOperationCompleted, userState);
        }
        
        private void OnGetHotelsOperationCompleted(object arg) {
            if ((this.GetHotelsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHotelsCompleted(this, new GetHotelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRoomsByHotel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetRoomsByHotel(Hotel hotel) {
            object[] results = this.Invoke("GetRoomsByHotel", new object[] {
                        hotel});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetRoomsByHotelAsync(Hotel hotel) {
            this.GetRoomsByHotelAsync(hotel, null);
        }
        
        /// <remarks/>
        public void GetRoomsByHotelAsync(Hotel hotel, object userState) {
            if ((this.GetRoomsByHotelOperationCompleted == null)) {
                this.GetRoomsByHotelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRoomsByHotelOperationCompleted);
            }
            this.InvokeAsync("GetRoomsByHotel", new object[] {
                        hotel}, this.GetRoomsByHotelOperationCompleted, userState);
        }
        
        private void OnGetRoomsByHotelOperationCompleted(object arg) {
            if ((this.GetRoomsByHotelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRoomsByHotelCompleted(this, new GetRoomsByHotelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindRooms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FindRooms(Amenities amenities, string city, string state) {
            object[] results = this.Invoke("FindRooms", new object[] {
                        amenities,
                        city,
                        state});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FindRoomsAsync(Amenities amenities, string city, string state) {
            this.FindRoomsAsync(amenities, city, state, null);
        }
        
        /// <remarks/>
        public void FindRoomsAsync(Amenities amenities, string city, string state, object userState) {
            if ((this.FindRoomsOperationCompleted == null)) {
                this.FindRoomsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindRoomsOperationCompleted);
            }
            this.InvokeAsync("FindRooms", new object[] {
                        amenities,
                        city,
                        state}, this.FindRoomsOperationCompleted, userState);
        }
        
        private void OnFindRoomsOperationCompleted(object arg) {
            if ((this.FindRoomsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindRoomsCompleted(this, new FindRoomsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindRoomsByHotel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FindRoomsByHotel(Hotel hotel, Amenities amenities) {
            object[] results = this.Invoke("FindRoomsByHotel", new object[] {
                        hotel,
                        amenities});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FindRoomsByHotelAsync(Hotel hotel, Amenities amenities) {
            this.FindRoomsByHotelAsync(hotel, amenities, null);
        }
        
        /// <remarks/>
        public void FindRoomsByHotelAsync(Hotel hotel, Amenities amenities, object userState) {
            if ((this.FindRoomsByHotelOperationCompleted == null)) {
                this.FindRoomsByHotelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindRoomsByHotelOperationCompleted);
            }
            this.InvokeAsync("FindRoomsByHotel", new object[] {
                        hotel,
                        amenities}, this.FindRoomsByHotelOperationCompleted, userState);
        }
        
        private void OnFindRoomsByHotelOperationCompleted(object arg) {
            if ((this.FindRoomsByHotelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindRoomsByHotelCompleted(this, new FindRoomsByHotelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckDates", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckDates(int roomID, System.DateTime reqStart, System.DateTime reqEnd) {
            object[] results = this.Invoke("CheckDates", new object[] {
                        roomID,
                        reqStart,
                        reqEnd});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckDatesAsync(int roomID, System.DateTime reqStart, System.DateTime reqEnd) {
            this.CheckDatesAsync(roomID, reqStart, reqEnd, null);
        }
        
        /// <remarks/>
        public void CheckDatesAsync(int roomID, System.DateTime reqStart, System.DateTime reqEnd, object userState) {
            if ((this.CheckDatesOperationCompleted == null)) {
                this.CheckDatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckDatesOperationCompleted);
            }
            this.InvokeAsync("CheckDates", new object[] {
                        roomID,
                        reqStart,
                        reqEnd}, this.CheckDatesOperationCompleted, userState);
        }
        
        private void OnCheckDatesOperationCompleted(object arg) {
            if ((this.CheckDatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckDatesCompleted(this, new CheckDatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Reserve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Reserve(Room room, Customer customer, Reservation reservation, string TravelSiteID, string TravelSitePassword) {
            object[] results = this.Invoke("Reserve", new object[] {
                        room,
                        customer,
                        reservation,
                        TravelSiteID,
                        TravelSitePassword});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ReserveAsync(Room room, Customer customer, Reservation reservation, string TravelSiteID, string TravelSitePassword) {
            this.ReserveAsync(room, customer, reservation, TravelSiteID, TravelSitePassword, null);
        }
        
        /// <remarks/>
        public void ReserveAsync(Room room, Customer customer, Reservation reservation, string TravelSiteID, string TravelSitePassword, object userState) {
            if ((this.ReserveOperationCompleted == null)) {
                this.ReserveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReserveOperationCompleted);
            }
            this.InvokeAsync("Reserve", new object[] {
                        room,
                        customer,
                        reservation,
                        TravelSiteID,
                        TravelSitePassword}, this.ReserveOperationCompleted, userState);
        }
        
        private void OnReserveOperationCompleted(object arg) {
            if ((this.ReserveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReserveCompleted(this, new ReserveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Room))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Hotel {
        
        private int idField;
        
        private string nameField;
        
        private string cityField;
        
        private string stateField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Reservation {
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private string emailField;
        
        private int roomIDField;
        
        private int hotelIDField;
        
        /// <remarks/>
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public int RoomID {
            get {
                return this.roomIDField;
            }
            set {
                this.roomIDField = value;
            }
        }
        
        /// <remarks/>
        public int HotelID {
            get {
                return this.hotelIDField;
            }
            set {
                this.hotelIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Customer {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string phoneField;
        
        private string emailField;
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Amenities {
        
        private bool hasFreeCoffeeField;
        
        private bool isSmokingField;
        
        private bool hasFreeWifiField;
        
        private string bedSizeField;
        
        private bool hasKitchenField;
        
        private bool freeBreakfastField;
        
        /// <remarks/>
        public bool HasFreeCoffee {
            get {
                return this.hasFreeCoffeeField;
            }
            set {
                this.hasFreeCoffeeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsSmoking {
            get {
                return this.isSmokingField;
            }
            set {
                this.isSmokingField = value;
            }
        }
        
        /// <remarks/>
        public bool HasFreeWifi {
            get {
                return this.hasFreeWifiField;
            }
            set {
                this.hasFreeWifiField = value;
            }
        }
        
        /// <remarks/>
        public string BedSize {
            get {
                return this.bedSizeField;
            }
            set {
                this.bedSizeField = value;
            }
        }
        
        /// <remarks/>
        public bool HasKitchen {
            get {
                return this.hasKitchenField;
            }
            set {
                this.hasKitchenField = value;
            }
        }
        
        /// <remarks/>
        public bool FreeBreakfast {
            get {
                return this.freeBreakfastField;
            }
            set {
                this.freeBreakfastField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Room : Hotel {
        
        private int roomIDField;
        
        private int roomNumField;
        
        private string roomDescField;
        
        private int comfortablySleepsField;
        
        private float priceField;
        
        /// <remarks/>
        public int RoomID {
            get {
                return this.roomIDField;
            }
            set {
                this.roomIDField = value;
            }
        }
        
        /// <remarks/>
        public int RoomNum {
            get {
                return this.roomNumField;
            }
            set {
                this.roomNumField = value;
            }
        }
        
        /// <remarks/>
        public string RoomDesc {
            get {
                return this.roomDescField;
            }
            set {
                this.roomDescField = value;
            }
        }
        
        /// <remarks/>
        public int ComfortablySleeps {
            get {
                return this.comfortablySleepsField;
            }
            set {
                this.comfortablySleepsField = value;
            }
        }
        
        /// <remarks/>
        public float Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetHotelsCompletedEventHandler(object sender, GetHotelsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHotelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHotelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetRoomsByHotelCompletedEventHandler(object sender, GetRoomsByHotelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRoomsByHotelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRoomsByHotelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void FindRoomsCompletedEventHandler(object sender, FindRoomsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindRoomsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindRoomsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void FindRoomsByHotelCompletedEventHandler(object sender, FindRoomsByHotelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindRoomsByHotelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindRoomsByHotelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void CheckDatesCompletedEventHandler(object sender, CheckDatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckDatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckDatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ReserveCompletedEventHandler(object sender, ReserveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReserveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReserveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591