//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace _3342DevStepFinal.Cars {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CarServiceSoap", Namespace="http://tempuri.org/")]
    public partial class CarService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetRentalCarAgenciesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCarsByAgencyOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindCarsOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindCarsByAgencyOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReserveOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CarService() {
            this.Url = global::_3342DevStepFinal.Properties.Settings.Default._3342DevStepFinal_Cars_CarService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetRentalCarAgenciesCompletedEventHandler GetRentalCarAgenciesCompleted;
        
        /// <remarks/>
        public event GetCarsByAgencyCompletedEventHandler GetCarsByAgencyCompleted;
        
        /// <remarks/>
        public event FindCarsCompletedEventHandler FindCarsCompleted;
        
        /// <remarks/>
        public event FindCarsByAgencyCompletedEventHandler FindCarsByAgencyCompleted;
        
        /// <remarks/>
        public event ReserveCompletedEventHandler ReserveCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRentalCarAgencies", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetRentalCarAgencies(string city, string state) {
            object[] results = this.Invoke("GetRentalCarAgencies", new object[] {
                        city,
                        state});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetRentalCarAgenciesAsync(string city, string state) {
            this.GetRentalCarAgenciesAsync(city, state, null);
        }
        
        /// <remarks/>
        public void GetRentalCarAgenciesAsync(string city, string state, object userState) {
            if ((this.GetRentalCarAgenciesOperationCompleted == null)) {
                this.GetRentalCarAgenciesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRentalCarAgenciesOperationCompleted);
            }
            this.InvokeAsync("GetRentalCarAgencies", new object[] {
                        city,
                        state}, this.GetRentalCarAgenciesOperationCompleted, userState);
        }
        
        private void OnGetRentalCarAgenciesOperationCompleted(object arg) {
            if ((this.GetRentalCarAgenciesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRentalCarAgenciesCompleted(this, new GetRentalCarAgenciesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCarsByAgency", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetCarsByAgency(Agency agency, string city, string state) {
            object[] results = this.Invoke("GetCarsByAgency", new object[] {
                        agency,
                        city,
                        state});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetCarsByAgencyAsync(Agency agency, string city, string state) {
            this.GetCarsByAgencyAsync(agency, city, state, null);
        }
        
        /// <remarks/>
        public void GetCarsByAgencyAsync(Agency agency, string city, string state, object userState) {
            if ((this.GetCarsByAgencyOperationCompleted == null)) {
                this.GetCarsByAgencyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCarsByAgencyOperationCompleted);
            }
            this.InvokeAsync("GetCarsByAgency", new object[] {
                        agency,
                        city,
                        state}, this.GetCarsByAgencyOperationCompleted, userState);
        }
        
        private void OnGetCarsByAgencyOperationCompleted(object arg) {
            if ((this.GetCarsByAgencyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCarsByAgencyCompleted(this, new GetCarsByAgencyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindCars", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FindCars(Requirements requirements, string city, string state) {
            object[] results = this.Invoke("FindCars", new object[] {
                        requirements,
                        city,
                        state});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FindCarsAsync(Requirements requirements, string city, string state) {
            this.FindCarsAsync(requirements, city, state, null);
        }
        
        /// <remarks/>
        public void FindCarsAsync(Requirements requirements, string city, string state, object userState) {
            if ((this.FindCarsOperationCompleted == null)) {
                this.FindCarsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindCarsOperationCompleted);
            }
            this.InvokeAsync("FindCars", new object[] {
                        requirements,
                        city,
                        state}, this.FindCarsOperationCompleted, userState);
        }
        
        private void OnFindCarsOperationCompleted(object arg) {
            if ((this.FindCarsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindCarsCompleted(this, new FindCarsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindCarsByAgency", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FindCarsByAgency(Agency agency, Requirements requirements, string city, string state) {
            object[] results = this.Invoke("FindCarsByAgency", new object[] {
                        agency,
                        requirements,
                        city,
                        state});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FindCarsByAgencyAsync(Agency agency, Requirements requirements, string city, string state) {
            this.FindCarsByAgencyAsync(agency, requirements, city, state, null);
        }
        
        /// <remarks/>
        public void FindCarsByAgencyAsync(Agency agency, Requirements requirements, string city, string state, object userState) {
            if ((this.FindCarsByAgencyOperationCompleted == null)) {
                this.FindCarsByAgencyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindCarsByAgencyOperationCompleted);
            }
            this.InvokeAsync("FindCarsByAgency", new object[] {
                        agency,
                        requirements,
                        city,
                        state}, this.FindCarsByAgencyOperationCompleted, userState);
        }
        
        private void OnFindCarsByAgencyOperationCompleted(object arg) {
            if ((this.FindCarsByAgencyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindCarsByAgencyCompleted(this, new FindCarsByAgencyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Reserve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Reserve(Agency agency, Car car, Customer customer, string TravelSiteID, string TravelSitePassword) {
            object[] results = this.Invoke("Reserve", new object[] {
                        agency,
                        car,
                        customer,
                        TravelSiteID,
                        TravelSitePassword});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ReserveAsync(Agency agency, Car car, Customer customer, string TravelSiteID, string TravelSitePassword) {
            this.ReserveAsync(agency, car, customer, TravelSiteID, TravelSitePassword, null);
        }
        
        /// <remarks/>
        public void ReserveAsync(Agency agency, Car car, Customer customer, string TravelSiteID, string TravelSitePassword, object userState) {
            if ((this.ReserveOperationCompleted == null)) {
                this.ReserveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReserveOperationCompleted);
            }
            this.InvokeAsync("Reserve", new object[] {
                        agency,
                        car,
                        customer,
                        TravelSiteID,
                        TravelSitePassword}, this.ReserveOperationCompleted, userState);
        }
        
        private void OnReserveOperationCompleted(object arg) {
            if ((this.ReserveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReserveCompleted(this, new ReserveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Agency {
        
        private int agencyIDField;
        
        private string nameField;
        
        private string cityField;
        
        private string stateField;
        
        /// <remarks/>
        public int agencyID {
            get {
                return this.agencyIDField;
            }
            set {
                this.agencyIDField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Customer {
        
        private int customerIDField;
        
        private string nameField;
        
        /// <remarks/>
        public int customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Car {
        
        private int carIDField;
        
        private string makeField;
        
        private string modelField;
        
        private int priceField;
        
        private int numDoorsField;
        
        private string ecoField;
        
        private int numPassengerField;
        
        private int agencyIDField;
        
        /// <remarks/>
        public int carID {
            get {
                return this.carIDField;
            }
            set {
                this.carIDField = value;
            }
        }
        
        /// <remarks/>
        public string make {
            get {
                return this.makeField;
            }
            set {
                this.makeField = value;
            }
        }
        
        /// <remarks/>
        public string model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public int price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public int numDoors {
            get {
                return this.numDoorsField;
            }
            set {
                this.numDoorsField = value;
            }
        }
        
        /// <remarks/>
        public string eco {
            get {
                return this.ecoField;
            }
            set {
                this.ecoField = value;
            }
        }
        
        /// <remarks/>
        public int numPassenger {
            get {
                return this.numPassengerField;
            }
            set {
                this.numPassengerField = value;
            }
        }
        
        /// <remarks/>
        public int agencyID {
            get {
                return this.agencyIDField;
            }
            set {
                this.agencyIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Requirements {
        
        private int priceField;
        
        private int numDoorField;
        
        private string ecoField;
        
        private int numPassengerField;
        
        /// <remarks/>
        public int price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public int numDoor {
            get {
                return this.numDoorField;
            }
            set {
                this.numDoorField = value;
            }
        }
        
        /// <remarks/>
        public string eco {
            get {
                return this.ecoField;
            }
            set {
                this.ecoField = value;
            }
        }
        
        /// <remarks/>
        public int numPassenger {
            get {
                return this.numPassengerField;
            }
            set {
                this.numPassengerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetRentalCarAgenciesCompletedEventHandler(object sender, GetRentalCarAgenciesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRentalCarAgenciesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRentalCarAgenciesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetCarsByAgencyCompletedEventHandler(object sender, GetCarsByAgencyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCarsByAgencyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCarsByAgencyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void FindCarsCompletedEventHandler(object sender, FindCarsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindCarsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindCarsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void FindCarsByAgencyCompletedEventHandler(object sender, FindCarsByAgencyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindCarsByAgencyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindCarsByAgencyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ReserveCompletedEventHandler(object sender, ReserveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReserveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReserveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591